/**
 * Opervia module catalog — describes Phase 1 capabilities in place.
 * Implementations remain in existing routes/services; this is metadata only.
 * Phase 2.6: each module declares domain-level capabilities (not authz).
 */
import type { ModuleId, OperviaModule } from './types';

export const MODULE_CATALOG: readonly OperviaModule[] = [
  {
    id: 'core',
    name: 'Platform Core',
    version: '1.0.0',
    dependencies: [],
    kind: 'core',
    capabilities: ['platform.auth', 'platform.settings', 'platform.audit'],
    routePrefixes: ['/api/auth', '/api/settings', '/api/audit-logs'],
    description: 'Auth, authorization, settings, audit, security middleware',
  },
  {
    id: 'customer',
    name: 'Customer',
    version: '1.0.0',
    dependencies: ['core'],
    kind: 'shared',
    capabilities: ['customer.manage'],
    routePrefixes: ['/api/customers', '/api/customers-search', '/api/crm'],
  },
  {
    id: 'product',
    name: 'Product',
    version: '1.0.0',
    dependencies: ['core', 'category'],
    kind: 'shared',
    capabilities: ['product.manage'],
    routePrefixes: ['/api/products'],
  },
  {
    id: 'category',
    name: 'Category',
    version: '1.0.0',
    dependencies: ['core'],
    kind: 'shared',
    capabilities: ['category.manage'],
    routePrefixes: ['/api/categories'],
  },
  {
    id: 'inventory',
    name: 'Inventory',
    version: '1.0.0',
    dependencies: ['product'],
    kind: 'shared',
    capabilities: ['inventory.stock'],
    description: 'Product stock counts + append-only movement ledger (v75+)',
    routePrefixes: ['/api/inventory'],
  },
  {
    id: 'pos',
    name: 'POS',
    version: '1.0.0',
    dependencies: ['product', 'order', 'payment'],
    kind: 'shared',
    capabilities: ['pos.sell'],
    routePrefixes: ['/api/pos-info'],
  },
  {
    id: 'order',
    name: 'Order',
    version: '1.0.0',
    dependencies: ['product', 'core'],
    kind: 'shared',
    capabilities: ['order.manage'],
    routePrefixes: ['/api/orders', '/api/order-items', '/api/held-orders'],
  },
  {
    id: 'payment',
    name: 'Payment',
    version: '1.0.0',
    dependencies: ['order'],
    kind: 'shared',
    capabilities: ['payment.tender'],
    routePrefixes: ['/api/bills', '/api/payment-methods'],
  },
  {
    id: 'refund',
    name: 'Refund',
    version: '1.0.0',
    dependencies: ['payment'],
    kind: 'shared',
    capabilities: ['refund.process'],
    routePrefixes: ['/api/refunds'],
  },
  {
    id: 'tax',
    name: 'Tax',
    version: '1.0.0',
    dependencies: ['core'],
    kind: 'shared',
    capabilities: ['tax.compute'],
    featureFlags: ['taxes_enabled'],
    routePrefixes: ['/api/tax', '/api/tax-packs'],
  },
  {
    id: 'shift',
    name: 'Shift',
    version: '1.0.0',
    dependencies: ['core', 'payment'],
    kind: 'shared',
    capabilities: ['shift.operate'],
    featureFlags: ['shifts_enabled'],
    routePrefixes: ['/api/shifts'],
  },
  {
    id: 'staff',
    name: 'Staff',
    version: '1.0.0',
    dependencies: ['core'],
    kind: 'shared',
    capabilities: ['staff.manage'],
    routePrefixes: ['/api/staff', '/api/users'],
  },
  {
    id: 'loyalty',
    name: 'Loyalty',
    version: '1.0.0',
    dependencies: ['customer', 'payment'],
    kind: 'shared',
    capabilities: ['loyalty.operate'],
    featureFlags: ['loyalty_enabled'],
  },
  {
    id: 'reporting',
    name: 'Reporting',
    version: '1.0.0',
    dependencies: ['core', 'payment'],
    kind: 'shared',
    capabilities: ['reporting.view'],
    routePrefixes: ['/api/reports'],
  },
  {
    id: 'printing',
    name: 'Printing',
    version: '1.0.0',
    dependencies: ['core'],
    kind: 'shared',
    capabilities: ['printing.output'],
    featureFlags: ['kot_printing_enabled'],
    routePrefixes: ['/api/printers'],
    description: 'Receipt printing shared; KOT printing restaurant-oriented',
  },
  {
    id: 'notification',
    name: 'Notification',
    version: '1.0.0',
    dependencies: ['core'],
    kind: 'shared',
    capabilities: ['notification.deliver'],
    routePrefixes: ['/api/whatsapp'],
    description: 'WhatsApp bill delivery (runtime gated by connection status)',
  },
  {
    id: 'backup',
    name: 'Backup',
    version: '1.0.0',
    dependencies: ['core'],
    kind: 'shared',
    capabilities: ['backup.operate'],
    routePrefixes: ['/api/database', '/api/database-tools'],
  },
  {
    id: 'tables',
    name: 'Tables',
    version: '1.0.0',
    dependencies: ['order'],
    kind: 'restaurant',
    capabilities: ['tables.manage'],
    featureFlags: ['tables_required'],
    routePrefixes: ['/api/tables'],
  },
  {
    id: 'kitchen',
    name: 'Kitchen',
    version: '1.0.0',
    dependencies: ['order', 'product'],
    kind: 'restaurant',
    capabilities: ['kitchen.stations'],
    routePrefixes: ['/api/kitchen', '/api/kitchen-stations'],
  },
  {
    id: 'kds',
    name: 'KDS',
    version: '1.0.0',
    dependencies: ['order', 'kitchen', 'product'],
    kind: 'restaurant',
    capabilities: ['kds.display'],
    featureFlags: ['kds_enabled'],
    routePrefixes: ['/api/kds', '/api/kds-info'],
  },
  {
    id: 'menu',
    name: 'Menu',
    version: '1.0.0',
    dependencies: ['product', 'category'],
    kind: 'restaurant',
    capabilities: ['menu.present'],
    routePrefixes: ['/api/menu'],
    description: 'Menu CSV import / restaurant catalog presentation',
  },
  {
    id: 'addons',
    name: 'Addons',
    version: '1.0.0',
    dependencies: ['product'],
    kind: 'restaurant',
    capabilities: ['addons.manage'],
    routePrefixes: ['/api/addon-groups'],
  },
] as const;

export const MODULE_IDS: readonly ModuleId[] = MODULE_CATALOG.map((m) => m.id);

const byId = new Map(MODULE_CATALOG.map((m) => [m.id, m]));

export function getCatalogModule(id: string): OperviaModule | undefined {
  return byId.get(id as ModuleId);
}
